const STATE_NAME = "TODO";

const SET_TODO = "SET_TODO";
const CREATE_TODO = "CREATE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const DELETE_TODO = "DELETE_TODO";
const DELETE_ALL_TODOS = "DELETE_ALL_TODOS";
const TOGGLE_ALL_TODOS = "TOGGLE_ALL_TODOS";
const UPDATE_TODO_STATUS = "UPDATE_TODO_STATUS";

export {
  STATE_NAME,
  SET_TODO,
  CREATE_TODO,
  DELETE_TODO,
  DELETE_ALL_TODOS,
  TOGGLE_ALL_TODOS,
  UPDATE_TODO_STATUS,
  UPDATE_TODO,
};
