export const TYPE_CALLBACK = {
    CREATE_TODO: 'CREATE_TODO',

    UPDATE_SHOWING_STATUS: 'UPDATE_SHOWING_STATUS',
    UPDATE_STATUS_BY_ID: 'UPDATE_STATUS_BY_ID',
    UPDATE_IS_IMPORTANT: 'UPDATE_IS_IMPORTANT',
    UPDATE_TODO: 'UPDATE_TODO',


    TOGGLE_ALL_TODO: 'TOGGLE_ALL_TODO',

    DELETE_ALL: 'DELETE_ALL',
    DELETE_ITEM_BY_ID: 'DELETE_ITEM_BY_ID',
}

export const MAP_SHOWING_TO_ACTIVE_MENU = {
    ALL: "ALL",
    ACTIVE: "ACTIVE",
    COMPLETED: "COMPLETED",
    CLEAR: "CLEAR",
    IMPORTANT: "IMPORTANT"
}