export const AUTH_TOKEN = "MANADO_TOKEN";
export const MANADO_DB = "MANADO_DB";

export const SET_TODO = "SET_TODO";
export const CREATE_TODO = "CREATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_ALL_TODOS = "DELETE_ALL_TODOS";
export const TOGGLE_ALL_TODOS = "TOGGLE_ALL_TODOS";
export const UPDATE_TODO_STATUS = "UPDATE_TODO_STATUS";
export const UPDATE_TODO_CONTENT = "UPDATE_TODO_CONTENT";
export const TRIGGER_REFRESH = "TRIGGER_REFRESH";

export const SET_USER = "SET_USER";
