export const SET_TODO_LIST = 'SET_TODO_LIST';
export const CREATE_TODO = 'CREATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_ALL_TODO_LIST = 'DELETE_ALL_TODO_LIST';
export const TOGGLE_ALL_TODO = 'TOGGLE_ALL_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
