export const GET_TODOS = 'GET_TODOS'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const CREATE_TODO = 'CREATE_TODO'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS'
export const DELETE_ALL_TODOS_SUCCESS = 'DELETE_ALL_TODOS_SUCCESS'
export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_STATUS_SUCCESS'
export const TOGGLE_ALL_TODOS = 'TOGGLE_ALL_TODOS'
export const TOGGLE_ALL_TODOS_SUCCESS = 'TOGGLE_ALL_TODOS_SUCCESS'

export const TODO_MAX_CONTENT_LENGTH = 60
