export enum ActionType {
  SET_TODO = "SET_TODO",
  CREATE_TODO = "CREATE_TODO",
  DELETE_TODO = "DELETE_TODO",
  DELETE_ALL_TODOS = "DELETE_ALL_TODOS",
  TOGGLE_ALL_TODOS = "TOGGLE_ALL_TODOS",
  UPDATE_TODO_STATUS = "UPDATE_TODO_STATUS",
  UPDATE_TODO_CONTENT = "UPDATE_TODO_CONTENT",
}
