name: ci

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd /home/
            #git clone https://github.com/trongcong/mana-do.git todos #should only clone once
            cd todos
            git checkout development
            git pull
            #printf "SKIP_PREFLIGHT_CHECK=true" > .env
            yarn install
            yarn build
